[project]
name = "ae-scraper"
version = "0.1.0"
description = "Post scraper for AmateurEngineering.com"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "feedparser>=6.0.11",
    "requests>=2.32.5",
]
